Below method was attempted, however the first line of each csv would not line break properly in the new csv; there were ~ 150 rows with only, of which only 11 had data past the first row. Concatenating csvs manually deemed faster than debugging in this case

https://www.freecodecamp.org/news/how-to-combine-multiple-csv-files-with-8-lines-of-code-265183e0854/

Historic data available from binance, csvs were downloaded and manually concatenated; 

https://data.binance.vision/?prefix=data/spot/monthly/klines/ETHUSDT/1m/

In [1]:
import os
import glob
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df1 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-01.csv", header=None)
df2 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-02.csv", header=None)
df3 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-03.csv", header=None)
df4 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-04.csv", header=None)
df5 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-05.csv", header=None)
df6 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-06.csv", header=None)
df7 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-07.csv", header=None)
df8 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-08.csv", header=None)
df9 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-09.csv", header=None)
df10 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-10.csv", header=None)
df11 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-11.csv", header=None)
df12 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2021-12.csv", header=None)
df13 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2022-01.csv", header=None)
df14 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2022-02.csv", header=None)
df15 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2022-03.csv", header=None)
df16 = pd.read_csv ("/content/drive/MyDrive/Practicum/Github/data/ETH/ETHUSDT-1m-2022-04.csv", header=None)

In [5]:
merged = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16])
merged = merged.rename(columns={0:'Open_time', 1:'Open', 2:'High', 3:'Low', 4:'Close', 5:'Volume',  
                        6:'Close_time', 7:'Quote_asset_volume', 8:'Number_of_trades', 
                        9:'Taker_buy_base_asset_volume',10:'Taker_buy_quote_asset_volume', 11:'Ignore'})

In [8]:
merged.tail()

,Open_time,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,Number_of_trades,Taker_buy_base_asset_volume,Taker_buy_quote_asset_volume,Ignore
43195,1651362900000,2728.73,2729.36,2726.57,2727.33,613.9795,1651362959999,1.674860e+06,573,324.5781,885338.356075,0
43196,1651362960000,2727.33,2728.66,2726.50,2728.30,464.1418,1651363019999,1.266108e+06,559,242.8939,662553.824136,0
43197,1651363020000,2728.30,2728.84,2725.14,2727.07,554.5839,1651363079999,1.512166e+06,635,314.9796,858724.596448,0
43198,1651363080000,2727.06,2728.10,2726.65,2727.89,526.3957,1651363139999,1.435656e+06,445,201.7612,550229.545791,0
43199,1651363140000,2727.89,2728.00,2726.38,2726.66,334.0688,1651363199999,9.110747e+05,433,181.3378,494539.920380,0

In [7]:
merged.to_csv('/content/drive/MyDrive/Practicum/Github/data/ETH/eth_price_data_2021-01-01_2022-04-30', sep=',', index=False)