# Transform block contract data into Contract Count Timeseries

### Import Libraries, Load data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from matplotlib.pyplot import figure

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df2 = pd.read_csv ('/content/drive/MyDrive/Practicum/Github/data/contracts 2021-11-26 to 2022-05-21/bq-results-20220511-193924-1652297975968.csv', header=0)
df2['block_timestamp'] = df2['block_timestamp'].str[:-3]
df2['block_timestamp'] = pd.to_datetime(df2['block_timestamp'], format = '%Y-%m-%d %H:%M')

In [ ]:
df2.head()

      block_timestamp  is_erc20  is_erc721
0 2022-05-11 19:32:48     False      False
1 2022-05-11 19:32:48     False      False
2 2022-05-11 19:32:08     False      False
3 2022-05-11 19:32:08     False      False
4 2022-05-11 19:32:08     False      False

In [ ]:
contract_binary = df2
contract_binary['contracts'] = 1
contract_binary['is_erc20'] = contract_binary['is_erc20'].astype(int)
contract_binary['is_erc721'] = contract_binary['is_erc721'].astype(int)
df2

            block_timestamp  is_erc20  is_erc721  contracts
0       2022-05-11 19:32:48         0          0          1
1       2022-05-11 19:32:48         0          0          1
2       2022-05-11 19:32:08         0          0          1
3       2022-05-11 19:32:08         0          0          1
4       2022-05-11 19:32:08         0          0          1
...                     ...       ...        ...        ...
2465166 2021-11-26 00:00:28         0          0          1
2465167 2021-11-26 00:00:28         0          0          1
2465168 2021-11-26 00:00:28         0          0          1
2465169 2021-11-26 00:00:10         0          0          1
2465170 2021-11-26 00:00:02         0          0          1

[2465171 rows x 4 columns]

In [ ]:
df2.to_csv('/content/drive/MyDrive/Practicum/Github/data/Contract counts 2021-11-26 to 2022-05-26', sep=',')